//go:build !ignore_autogenerated

/*
Copyright 2025 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigration) DeepCopyInto(out *VirtualMachineStorageMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigration.
func (in *VirtualMachineStorageMigration) DeepCopy() *VirtualMachineStorageMigration {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineStorageMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationList) DeepCopyInto(out *VirtualMachineStorageMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineStorageMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationList.
func (in *VirtualMachineStorageMigrationList) DeepCopy() *VirtualMachineStorageMigrationList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineStorageMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlan) DeepCopyInto(out *VirtualMachineStorageMigrationPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlan.
func (in *VirtualMachineStorageMigrationPlan) DeepCopy() *VirtualMachineStorageMigrationPlan {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineStorageMigrationPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanDestinationPVC) DeepCopyInto(out *VirtualMachineStorageMigrationPlanDestinationPVC) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]VirtualMachineStorageMigrationPlanAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.VolumeMode != nil {
		in, out := &in.VolumeMode, &out.VolumeMode
		*out = new(v1.PersistentVolumeMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanDestinationPVC.
func (in *VirtualMachineStorageMigrationPlanDestinationPVC) DeepCopy() *VirtualMachineStorageMigrationPlanDestinationPVC {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanDestinationPVC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanList) DeepCopyInto(out *VirtualMachineStorageMigrationPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineStorageMigrationPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanList.
func (in *VirtualMachineStorageMigrationPlanList) DeepCopy() *VirtualMachineStorageMigrationPlanList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineStorageMigrationPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanSourcePVC) DeepCopyInto(out *VirtualMachineStorageMigrationPlanSourcePVC) {
	*out = *in
	in.SourcePVC.DeepCopyInto(&out.SourcePVC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanSourcePVC.
func (in *VirtualMachineStorageMigrationPlanSourcePVC) DeepCopy() *VirtualMachineStorageMigrationPlanSourcePVC {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanSourcePVC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanSpec) DeepCopyInto(out *VirtualMachineStorageMigrationPlanSpec) {
	*out = *in
	if in.VirtualMachines != nil {
		in, out := &in.VirtualMachines, &out.VirtualMachines
		*out = make([]VirtualMachineStorageMigrationPlanVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanSpec.
func (in *VirtualMachineStorageMigrationPlanSpec) DeepCopy() *VirtualMachineStorageMigrationPlanSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanStatus) DeepCopyInto(out *VirtualMachineStorageMigrationPlanStatus) {
	*out = *in
	if in.ReadyMigrations != nil {
		in, out := &in.ReadyMigrations, &out.ReadyMigrations
		*out = make([]VirtualMachineStorageMigrationPlanStatusVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InvalidMigrations != nil {
		in, out := &in.InvalidMigrations, &out.InvalidMigrations
		*out = make([]VirtualMachineStorageMigrationPlanStatusVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InProgressMigrations != nil {
		in, out := &in.InProgressMigrations, &out.InProgressMigrations
		*out = make([]VirtualMachineStorageMigrationPlanStatusVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletedMigrations != nil {
		in, out := &in.CompletedMigrations, &out.CompletedMigrations
		*out = make([]VirtualMachineStorageMigrationPlanStatusVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailedMigrations != nil {
		in, out := &in.FailedMigrations, &out.FailedMigrations
		*out = make([]VirtualMachineStorageMigrationPlanStatusVirtualMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Suffix != nil {
		in, out := &in.Suffix, &out.Suffix
		*out = new(string)
		**out = **in
	}
	in.Conditions.DeepCopyInto(&out.Conditions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanStatus.
func (in *VirtualMachineStorageMigrationPlanStatus) DeepCopy() *VirtualMachineStorageMigrationPlanStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanStatusVirtualMachine) DeepCopyInto(out *VirtualMachineStorageMigrationPlanStatusVirtualMachine) {
	*out = *in
	in.VirtualMachineStorageMigrationPlanVirtualMachine.DeepCopyInto(&out.VirtualMachineStorageMigrationPlanVirtualMachine)
	if in.SourcePVCs != nil {
		in, out := &in.SourcePVCs, &out.SourcePVCs
		*out = make([]VirtualMachineStorageMigrationPlanSourcePVC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanStatusVirtualMachine.
func (in *VirtualMachineStorageMigrationPlanStatusVirtualMachine) DeepCopy() *VirtualMachineStorageMigrationPlanStatusVirtualMachine {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanStatusVirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanTargetMigrationPVC) DeepCopyInto(out *VirtualMachineStorageMigrationPlanTargetMigrationPVC) {
	*out = *in
	in.DestinationPVC.DeepCopyInto(&out.DestinationPVC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanTargetMigrationPVC.
func (in *VirtualMachineStorageMigrationPlanTargetMigrationPVC) DeepCopy() *VirtualMachineStorageMigrationPlanTargetMigrationPVC {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanTargetMigrationPVC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationPlanVirtualMachine) DeepCopyInto(out *VirtualMachineStorageMigrationPlanVirtualMachine) {
	*out = *in
	if in.TargetMigrationPVCs != nil {
		in, out := &in.TargetMigrationPVCs, &out.TargetMigrationPVCs
		*out = make([]VirtualMachineStorageMigrationPlanTargetMigrationPVC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationPlanVirtualMachine.
func (in *VirtualMachineStorageMigrationPlanVirtualMachine) DeepCopy() *VirtualMachineStorageMigrationPlanVirtualMachine {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationPlanVirtualMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationSpec) DeepCopyInto(out *VirtualMachineStorageMigrationSpec) {
	*out = *in
	if in.VirtualMachineStorageMigrationPlanRef != nil {
		in, out := &in.VirtualMachineStorageMigrationPlanRef, &out.VirtualMachineStorageMigrationPlanRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationSpec.
func (in *VirtualMachineStorageMigrationSpec) DeepCopy() *VirtualMachineStorageMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineStorageMigrationStatus) DeepCopyInto(out *VirtualMachineStorageMigrationStatus) {
	*out = *in
	in.Conditions.DeepCopyInto(&out.Conditions)
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunningMigrations != nil {
		in, out := &in.RunningMigrations, &out.RunningMigrations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompletedMigrations != nil {
		in, out := &in.CompletedMigrations, &out.CompletedMigrations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineStorageMigrationStatus.
func (in *VirtualMachineStorageMigrationStatus) DeepCopy() *VirtualMachineStorageMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineStorageMigrationStatus)
	in.DeepCopyInto(out)
	return out
}
