/*
Copyright 2025 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	migrationcontrollerv1alpha1 "kubevirt.io/kubevirt-migration-controller/api/migrationcontroller/v1alpha1"
	scheme "kubevirt.io/kubevirt-migration-controller/pkg/client/clientset/versioned/scheme"
)

// VirtualMachineStorageMigrationPlansGetter has a method to return a VirtualMachineStorageMigrationPlanInterface.
// A group's client should implement this interface.
type VirtualMachineStorageMigrationPlansGetter interface {
	VirtualMachineStorageMigrationPlans(namespace string) VirtualMachineStorageMigrationPlanInterface
}

// VirtualMachineStorageMigrationPlanInterface has methods to work with VirtualMachineStorageMigrationPlan resources.
type VirtualMachineStorageMigrationPlanInterface interface {
	Create(ctx context.Context, virtualMachineStorageMigrationPlan *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, opts v1.CreateOptions) (*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, error)
	Update(ctx context.Context, virtualMachineStorageMigrationPlan *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, opts v1.UpdateOptions) (*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineStorageMigrationPlan *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, opts v1.UpdateOptions) (*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, err error)
	VirtualMachineStorageMigrationPlanExpansion
}

// virtualMachineStorageMigrationPlans implements VirtualMachineStorageMigrationPlanInterface
type virtualMachineStorageMigrationPlans struct {
	*gentype.ClientWithList[*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlanList]
}

// newVirtualMachineStorageMigrationPlans returns a VirtualMachineStorageMigrationPlans
func newVirtualMachineStorageMigrationPlans(c *MigrationcontrollerV1alpha1Client, namespace string) *virtualMachineStorageMigrationPlans {
	return &virtualMachineStorageMigrationPlans{
		gentype.NewClientWithList[*migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan, *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlanList](
			"virtualmachinestoragemigrationplans",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan {
				return &migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlan{}
			},
			func() *migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlanList {
				return &migrationcontrollerv1alpha1.VirtualMachineStorageMigrationPlanList{}
			},
		),
	}
}
